name: PM Glass
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48995
title: Creative Green Glass Works
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#4593ff'
    - '#000000'
    - '#eddbb3'
    - '#bb602c'
    - '#0820fe'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
